PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS images (
	dhash INTEGER NOT NULL PRIMARY KEY,
	path TEXT NOT NULL UNIQUE,
	size INTEGER NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS recent ON images (created_at DESC);

CREATE TABLE IF NOT EXISTS tags (
  label TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS image_tags (
  label TEXT NOT NULL,
  dhash INTEGER NOT NULL,
  PRIMARY KEY (label, dhash),
  FOREIGN KEY (dhash) REFERENCES images (dhash) ON DELETE CASCADE,
  FOREIGN KEY (label) REFERENCES tags (label) ON DELETE CASCADE
);